# 反向代理
upstream oa{
  server unix:///data/sock/oa.sock;
}

# 虚拟主机
server {
  # 监听80端口
  listen 80;
  # 设置服务器域名
  server_name 121.41.67.132 127.0.0.1;
  # 设置编码方式
  charset utf-8;
  # 客户端请求服务器携带最大的数据
  client_max_body_size 10M;
  # 访问首页，直接返回vue项目的index.html文件
  # 注意：这里写的所有地址都是Docker容器中的地址
  location / {
    root /www/dist;
    index index.html;
  }
  # 访问vue项目的静态文件
  location /assets {
    alias /www/dist/assets;
  }
  # 访问django项目的的静态文件
  location /static {
    alias /www/static;
  }
  # 访问django项目的api
  location /api {
    include /etc/nginx/uwsgi_params;
    uwsgi_pass oa;
  }
  # nginx日志
  access_log /data/log/access.log;
  error_log /data/log/error.log;
}